name: CI

on: [push]

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ruby version specified in .ruby-version
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install gem bundle
        run: |
          gem install bundler
          bundle install
  rspec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install Ruby (version given by .ruby-version) and Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # - name: Prepare database for testing
      #   run: bundle exec rails db:prepare

      - name: Run rspec
        run: bundle exec rspec spec -fd
